### ISSUE TITLE
Templates are not loading

### ISSUE THREAD

**Issue by stratosgear** [ariera/ariera.github.io#1]
Hi there,

Regarding your `2017-09-26-django-webpack-vue-js-setting-up-a-new-project-that-s-easy-to-develop-and-deploy-part-1` article...

The django template `my_project/spa.html` does **not** load unless you edit the `./my_project/settings.py` file and fix the `TEMPLATES` setting to use the `/templates` directory that you created to store the templates into, like:

       'DIRS': ['./templates/'],

I would also remove the `my_project` prefix since all the templates in that project, ought to belong in the same project, so an extra path of `my_project` does not seem to offer any added value.

Finally I would really like to see a cleaner separation of backend and frontend paths so the files are not all mixed in the same root folder, but this is something that I'm working to clear myself.

Thanks for the initial workflow!

**Comment by stratosgear** [comment]
And I forgot the mention that your code formatting for the templates snippets includes a `{\%` (note the backslash **\\**) that can easily throw someone off, especially a newbie like me.   Obviously the backslash should **not** be there.

**Comment by stratosgear** [comment]
You're also missing a:

    var BundleTracker = require('webpack-bundle-tracker');

in the `./build/webpack.base.conf.js`

**Comment by stratosgear** [comment]
You also have a rogue space in:

    var hotClient = require('webpack-hot-middleware/client?noInfo=true&reload=true&path=http://localhost:8080/__<HERE>webpack_hmr')

**Comment by ariera** [comment]
wonderful feedback, thank you very much.
Hope it helped you nevertheless :)
I'll update ASAP
